### ISSUE TITLE
Пространство имен

### ISSUE THREAD

**Issue by vitkarpov** [vitkarpov/jblocks#1]
Для объявления нового блока:

```js
$.jblocks('define', {
    events: { ... },
    methods: { ... }
});
```

Для инициализации и уничтожения блоков:

```js
$(document).jblocks('init');
$(document).jblocks('destroy');
```

Для получения экземпляров блоков:

```js
$('.foo').jblocks('get').each(function() {
    // this — экземпляр блока
})
```

**Comment by vitkarpov** [comment]
@sergcen Привет! Заметил, что ты форкнул репо и добавил пространство имен в свой мастер, спасибо за участие.

Было бы круто, если бы ты сделал пул реквест в основной репо с этими изменения, однако сперва стоит договориться про АПИ.

Что скажешь?

**Comment by sergcen** [comment]
Привет! Сам хотел написать что то подобное, тут как раз увидел на хабре.
Да, давай договоримся. Ты предлагаешь для объявления нового блока $.jblocks('define',{...})?

На мой взгляд в старом варианте объявление блока более очевидное, в плане читабельности кода, как ты думаешь?
По поводу остального согласен.

**Comment by vitkarpov** [comment]
В плане читабельности, возможно, очевиднее.

Однако, так мы сможем сохранить единообразие с остальными методами и легко добавить новые в то же пространство имен, если нужно.

Кроме того, такой  способ (первый аргумент — название метода, а сама функция по имени плагина) общепринятый в мире jquery-плагинов.

**Comment by vitkarpov** [comment]
https://github.com/vitkarpov/jblocks/pull/2

**Comment by sergcen** [comment]
@vitkarpov 
может вместо $.jblocks('define', {}); использовать $.jblocks({}). Один статический метод для создания блока. В будущем можно реализовать обратную совместимость даже если потребуется добавить новые статические методы, проверяя первый аргумент на тип.

**Comment by vitkarpov** [comment]
@sergcen 

> может вместо $.jblocks('define', {}); использовать $.jblocks({})

Да, вроде неплохо. Давай так и поступим.

**Comment by vitkarpov** [comment]
Done
