### ISSUE TITLE
Demo link in README.md not working

### ISSUE THREAD

**Issue by xenongattz** [vitkarpov/jblocks#21]
Just 404 for link <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jblocks/1.1.0/jblocks.js"></script>

**Comment by vitkarpov** [comment]
Sorry, seems there's no 1.1.0 version on cdnjs :( You can check what the latter has [on this page](https://cdnjs.com/libraries/jblocks).

I'll check out what's happening (cdnjs claims there's autoupdate from npm).

**Comment by vitkarpov** [comment]
d8a1d50710b7dd6efabc62d7b742613848c5797c
