### ISSUE TITLE
Some events for some methods

### ISSUE THREAD

**Issue by 1993-smite** [vitkarpov/jblocks#28]
How add some events to component to methods bindings

**Comment by vitkarpov** [comment]
@1993-smite hey, thanks for opening this issue, I'm sorry I didn't spot it right away 😊 

I'm not sure I get your question. Could you, pls, make an example of what problem you're trying to solve?

I can answer using my intuition.

That's how you can declare events:

```js
   events: {
        'click .js-inc': 'inc',
        'click .js-dec': 'dec'
    },
```

Keys in this object mean: "event name" (whitespace) "selector of a node inside" and values mean names of methods you're supposed to declare in the `methods` section.

Functions are bound to a component's instances automatically.
